using FraFactu.Domain.Entities.Catalogos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FraFactu.Infrastructure.Persistence.Configurations;

public class CatDistritoConfig : IEntityTypeConfiguration<CatDistrito>
{
    public void Configure(EntityTypeBuilder<CatDistrito> builder)
    {
        builder.ToTable("cat_distrito");

        builder.HasKey(x => x.Id);
        builder.Property(x => x.Codigo).HasMaxLength(4).IsRequired();
        builder.Property(x => x.Valor).HasMaxLength(100).IsRequired();
        builder.Property(x => x.CodigoDepartamento).HasMaxLength(2).IsRequired();
        builder.Property(x => x.CodigoMunicipio).HasMaxLength(4).IsRequired();

        // Índice por la triada para resolver el distrito desde Depto+Municipio.
        builder.HasIndex(x => new { x.CodigoDepartamento, x.CodigoMunicipio, x.Codigo })
            .HasDatabaseName("IX_cat_distrito_depto_muni_codigo");

        // Seed CAT-008 (Catálogo de Facturación Electrónica V1.0, 05/2026).
        // Código = CAT-008 (único por departamento). CodigoMunicipio = CAT-013 (municipio
        // agrupado al que pertenece el distrito). La llave real es la triada Depto→Muni→Distrito.
        builder.HasData(SeedData);
    }

    /// <summary>Seed CAT-008 expuesto para validación de integridad en tests.</summary>
    public static readonly CatDistrito[] SeedData = new CatDistrito[]
    {
            new CatDistrito { Id = 1, Codigo = "00", Valor = "Otro (Para extranjeros)", CodigoDepartamento = "00", CodigoMunicipio = "00" },

            // --- AHUACHAPÁN (01) | N=13, C=14, S=15 ---
            new CatDistrito { Id = 2, Codigo = "01", Valor = "Ahuachapán", CodigoDepartamento = "01", CodigoMunicipio = "14" },
            new CatDistrito { Id = 3, Codigo = "02", Valor = "Apaneca", CodigoDepartamento = "01", CodigoMunicipio = "14" },
            new CatDistrito { Id = 4, Codigo = "03", Valor = "Atiquizaya", CodigoDepartamento = "01", CodigoMunicipio = "13" },
            new CatDistrito { Id = 5, Codigo = "04", Valor = "Concepción de Ataco", CodigoDepartamento = "01", CodigoMunicipio = "14" },
            new CatDistrito { Id = 6, Codigo = "05", Valor = "El Refugio", CodigoDepartamento = "01", CodigoMunicipio = "13" },
            new CatDistrito { Id = 7, Codigo = "06", Valor = "Guaymango", CodigoDepartamento = "01", CodigoMunicipio = "15" },
            new CatDistrito { Id = 8, Codigo = "07", Valor = "Jujutla", CodigoDepartamento = "01", CodigoMunicipio = "15" },
            new CatDistrito { Id = 9, Codigo = "08", Valor = "San Francisco Menéndez", CodigoDepartamento = "01", CodigoMunicipio = "15" },
            new CatDistrito { Id = 10, Codigo = "09", Valor = "San Lorenzo", CodigoDepartamento = "01", CodigoMunicipio = "13" },
            new CatDistrito { Id = 11, Codigo = "10", Valor = "San Pedro Puxtla", CodigoDepartamento = "01", CodigoMunicipio = "15" },
            new CatDistrito { Id = 12, Codigo = "11", Valor = "Tacuba", CodigoDepartamento = "01", CodigoMunicipio = "14" },
            new CatDistrito { Id = 13, Codigo = "12", Valor = "Turín", CodigoDepartamento = "01", CodigoMunicipio = "13" },

            // --- SANTA ANA (02) | N=14, C=15, E=16, O=17 ---
            new CatDistrito { Id = 14, Codigo = "01", Valor = "Candelaria de la Frontera", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 15, Codigo = "02", Valor = "Coatepeque", CodigoDepartamento = "02", CodigoMunicipio = "16" },
            new CatDistrito { Id = 16, Codigo = "03", Valor = "Chalchuapa", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 17, Codigo = "04", Valor = "El Congo", CodigoDepartamento = "02", CodigoMunicipio = "16" },
            new CatDistrito { Id = 18, Codigo = "05", Valor = "El Porvenir", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 19, Codigo = "06", Valor = "Masahuat", CodigoDepartamento = "02", CodigoMunicipio = "14" },
            new CatDistrito { Id = 20, Codigo = "07", Valor = "Metapán", CodigoDepartamento = "02", CodigoMunicipio = "14" },
            new CatDistrito { Id = 21, Codigo = "08", Valor = "San Antonio Pajonal", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 22, Codigo = "09", Valor = "San Sebastián Salitrillo", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 23, Codigo = "10", Valor = "Santa Ana", CodigoDepartamento = "02", CodigoMunicipio = "15" },
            new CatDistrito { Id = 24, Codigo = "11", Valor = "Santa Rosa Guachipilín", CodigoDepartamento = "02", CodigoMunicipio = "14" },
            new CatDistrito { Id = 25, Codigo = "12", Valor = "Santiago de la Frontera", CodigoDepartamento = "02", CodigoMunicipio = "17" },
            new CatDistrito { Id = 26, Codigo = "13", Valor = "Texistepeque", CodigoDepartamento = "02", CodigoMunicipio = "14" },

            // --- SONSONATE (03) | N=17, C=18, E=19, O=20 ---
            new CatDistrito { Id = 27, Codigo = "01", Valor = "Acajutla", CodigoDepartamento = "03", CodigoMunicipio = "20" },
            new CatDistrito { Id = 28, Codigo = "02", Valor = "Armenia", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 29, Codigo = "03", Valor = "Caluco", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 30, Codigo = "04", Valor = "Cuisnahuat", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 31, Codigo = "05", Valor = "Santa Isabel Ishuatán", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 32, Codigo = "06", Valor = "Izalco", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 33, Codigo = "07", Valor = "Juayúa", CodigoDepartamento = "03", CodigoMunicipio = "17" },
            new CatDistrito { Id = 34, Codigo = "08", Valor = "Nahuizalco", CodigoDepartamento = "03", CodigoMunicipio = "17" },
            new CatDistrito { Id = 35, Codigo = "09", Valor = "Nahulingo", CodigoDepartamento = "03", CodigoMunicipio = "18" },
            new CatDistrito { Id = 36, Codigo = "10", Valor = "Salcoatitán", CodigoDepartamento = "03", CodigoMunicipio = "17" },
            new CatDistrito { Id = 37, Codigo = "11", Valor = "San Antonio del Monte", CodigoDepartamento = "03", CodigoMunicipio = "18" },
            new CatDistrito { Id = 38, Codigo = "12", Valor = "San Julián", CodigoDepartamento = "03", CodigoMunicipio = "19" },
            new CatDistrito { Id = 39, Codigo = "13", Valor = "Santa Catarina Masahuat", CodigoDepartamento = "03", CodigoMunicipio = "17" },
            new CatDistrito { Id = 40, Codigo = "14", Valor = "Santo Domingo de Guzmán", CodigoDepartamento = "03", CodigoMunicipio = "18" },
            new CatDistrito { Id = 41, Codigo = "15", Valor = "Sonsonate", CodigoDepartamento = "03", CodigoMunicipio = "18" },
            new CatDistrito { Id = 42, Codigo = "16", Valor = "Sonzacate", CodigoDepartamento = "03", CodigoMunicipio = "18" },

            // --- CHALATENANGO (04) | N=34, C=35, S=36 ---
            new CatDistrito { Id = 43, Codigo = "01", Valor = "Agua Caliente", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 44, Codigo = "02", Valor = "Arcatao", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 45, Codigo = "03", Valor = "Azacualpa", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 46, Codigo = "04", Valor = "Citalá", CodigoDepartamento = "04", CodigoMunicipio = "34" },
            new CatDistrito { Id = 47, Codigo = "05", Valor = "Comalapa", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 48, Codigo = "06", Valor = "Concepción Quezaltepeque", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 49, Codigo = "07", Valor = "Chalatenango", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 50, Codigo = "08", Valor = "Dulce Nombre de María", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 51, Codigo = "09", Valor = "El Carrizal", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 52, Codigo = "10", Valor = "El Paraíso", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 53, Codigo = "11", Valor = "La Laguna", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 54, Codigo = "12", Valor = "La Palma", CodigoDepartamento = "04", CodigoMunicipio = "34" },
            new CatDistrito { Id = 55, Codigo = "13", Valor = "La Reina", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 56, Codigo = "14", Valor = "Las Vueltas", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 57, Codigo = "15", Valor = "Nombre de Jesús", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 58, Codigo = "16", Valor = "Nueva Concepción", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 59, Codigo = "17", Valor = "Nueva Trinidad", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 60, Codigo = "18", Valor = "Ojos de Agua", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 61, Codigo = "19", Valor = "Potonico", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 62, Codigo = "20", Valor = "San Antonio de la Cruz", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 63, Codigo = "21", Valor = "San Antonio Los Ranchos", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 64, Codigo = "22", Valor = "San Fernando", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 65, Codigo = "23", Valor = "San Francisco Lempa", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 66, Codigo = "24", Valor = "San Francisco Morazán", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 67, Codigo = "25", Valor = "San Ignacio", CodigoDepartamento = "04", CodigoMunicipio = "34" },
            new CatDistrito { Id = 68, Codigo = "26", Valor = "San Isidro Labrador", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 69, Codigo = "27", Valor = "San José Cancasque", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 70, Codigo = "28", Valor = "San José Las Flores", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 71, Codigo = "29", Valor = "San Luis del Carmen", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 72, Codigo = "30", Valor = "San Miguel de Mercedes", CodigoDepartamento = "04", CodigoMunicipio = "36" },
            new CatDistrito { Id = 73, Codigo = "31", Valor = "San Rafael", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 74, Codigo = "32", Valor = "Santa Rita", CodigoDepartamento = "04", CodigoMunicipio = "35" },
            new CatDistrito { Id = 75, Codigo = "33", Valor = "Tejutla", CodigoDepartamento = "04", CodigoMunicipio = "35" },

            // --- LA LIBERTAD (05) | N=23, C=24, O=25, E=26, Costa=27, S=28 ---
            new CatDistrito { Id = 76, Codigo = "01", Valor = "Antiguo Cuscatlán", CodigoDepartamento = "05", CodigoMunicipio = "26" },
            new CatDistrito { Id = 77, Codigo = "02", Valor = "Ciudad Arce", CodigoDepartamento = "05", CodigoMunicipio = "24" },
            new CatDistrito { Id = 78, Codigo = "03", Valor = "Colón", CodigoDepartamento = "05", CodigoMunicipio = "25" },
            new CatDistrito { Id = 79, Codigo = "04", Valor = "Comasagua", CodigoDepartamento = "05", CodigoMunicipio = "28" },
            new CatDistrito { Id = 80, Codigo = "05", Valor = "Chiltiupán", CodigoDepartamento = "05", CodigoMunicipio = "27" },
            new CatDistrito { Id = 81, Codigo = "06", Valor = "Huizúcar", CodigoDepartamento = "05", CodigoMunicipio = "26" },
            new CatDistrito { Id = 82, Codigo = "07", Valor = "Jayaque", CodigoDepartamento = "05", CodigoMunicipio = "25" },
            new CatDistrito { Id = 83, Codigo = "08", Valor = "Jicalapa", CodigoDepartamento = "05", CodigoMunicipio = "27" },
            new CatDistrito { Id = 84, Codigo = "09", Valor = "La Libertad", CodigoDepartamento = "05", CodigoMunicipio = "27" },
            new CatDistrito { Id = 85, Codigo = "10", Valor = "Nuevo Cuscatlán", CodigoDepartamento = "05", CodigoMunicipio = "26" },
            new CatDistrito { Id = 86, Codigo = "11", Valor = "Santa Tecla", CodigoDepartamento = "05", CodigoMunicipio = "28" },
            new CatDistrito { Id = 87, Codigo = "12", Valor = "Quezaltepeque", CodigoDepartamento = "05", CodigoMunicipio = "23" },
            new CatDistrito { Id = 88, Codigo = "13", Valor = "Sacacoyo", CodigoDepartamento = "05", CodigoMunicipio = "25" },
            new CatDistrito { Id = 89, Codigo = "14", Valor = "San José Villanueva", CodigoDepartamento = "05", CodigoMunicipio = "26" },
            new CatDistrito { Id = 90, Codigo = "15", Valor = "San Juan Opico", CodigoDepartamento = "05", CodigoMunicipio = "24" },
            new CatDistrito { Id = 91, Codigo = "16", Valor = "San Matías", CodigoDepartamento = "05", CodigoMunicipio = "23" },
            new CatDistrito { Id = 92, Codigo = "17", Valor = "San Pablo Tacachico", CodigoDepartamento = "05", CodigoMunicipio = "23" },
            new CatDistrito { Id = 93, Codigo = "18", Valor = "Tamanique", CodigoDepartamento = "05", CodigoMunicipio = "27" },
            new CatDistrito { Id = 94, Codigo = "19", Valor = "Talnique", CodigoDepartamento = "05", CodigoMunicipio = "25" },
            new CatDistrito { Id = 95, Codigo = "20", Valor = "Teotepeque", CodigoDepartamento = "05", CodigoMunicipio = "27" },
            new CatDistrito { Id = 96, Codigo = "21", Valor = "Tepecoyo", CodigoDepartamento = "05", CodigoMunicipio = "25" },
            new CatDistrito { Id = 97, Codigo = "22", Valor = "Zaragoza", CodigoDepartamento = "05", CodigoMunicipio = "26" },

            // --- SAN SALVADOR (06) | N=20, O=21, E=22, C=23, S=24 ---
            new CatDistrito { Id = 98, Codigo = "01", Valor = "Aguilares", CodigoDepartamento = "06", CodigoMunicipio = "20" },
            new CatDistrito { Id = 99, Codigo = "02", Valor = "Apopa", CodigoDepartamento = "06", CodigoMunicipio = "21" },
            new CatDistrito { Id = 100, Codigo = "03", Valor = "Ayutuxtepeque", CodigoDepartamento = "06", CodigoMunicipio = "23" },
            new CatDistrito { Id = 101, Codigo = "04", Valor = "Cuscatancingo", CodigoDepartamento = "06", CodigoMunicipio = "23" },
            new CatDistrito { Id = 102, Codigo = "05", Valor = "El Paisnal", CodigoDepartamento = "06", CodigoMunicipio = "20" },
            new CatDistrito { Id = 103, Codigo = "06", Valor = "Guazapa", CodigoDepartamento = "06", CodigoMunicipio = "20" },
            new CatDistrito { Id = 104, Codigo = "07", Valor = "Ilopango", CodigoDepartamento = "06", CodigoMunicipio = "22" },
            new CatDistrito { Id = 105, Codigo = "08", Valor = "Mejicanos", CodigoDepartamento = "06", CodigoMunicipio = "23" },
            new CatDistrito { Id = 106, Codigo = "09", Valor = "Nejapa", CodigoDepartamento = "06", CodigoMunicipio = "21" },
            new CatDistrito { Id = 107, Codigo = "10", Valor = "Panchimalco", CodigoDepartamento = "06", CodigoMunicipio = "24" },
            new CatDistrito { Id = 108, Codigo = "11", Valor = "Rosario de Mora", CodigoDepartamento = "06", CodigoMunicipio = "24" },
            new CatDistrito { Id = 109, Codigo = "12", Valor = "San Marcos", CodigoDepartamento = "06", CodigoMunicipio = "24" },
            new CatDistrito { Id = 110, Codigo = "13", Valor = "San Martín", CodigoDepartamento = "06", CodigoMunicipio = "22" },
            new CatDistrito { Id = 111, Codigo = "14", Valor = "San Salvador", CodigoDepartamento = "06", CodigoMunicipio = "23" },
            new CatDistrito { Id = 112, Codigo = "15", Valor = "Santiago Texacuangos", CodigoDepartamento = "06", CodigoMunicipio = "24" },
            new CatDistrito { Id = 113, Codigo = "16", Valor = "Santo Tomás", CodigoDepartamento = "06", CodigoMunicipio = "24" },
            new CatDistrito { Id = 114, Codigo = "17", Valor = "Soyapango", CodigoDepartamento = "06", CodigoMunicipio = "22" },
            new CatDistrito { Id = 115, Codigo = "18", Valor = "Tonacatepeque", CodigoDepartamento = "06", CodigoMunicipio = "22" },
            new CatDistrito { Id = 116, Codigo = "19", Valor = "Ciudad Delgado", CodigoDepartamento = "06", CodigoMunicipio = "23" },

            // --- CUSCATLÁN (07) | N=17, S=18 ---
            new CatDistrito { Id = 117, Codigo = "01", Valor = "Candelaria", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 118, Codigo = "02", Valor = "Cojutepeque", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 119, Codigo = "03", Valor = "El Carmen", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 120, Codigo = "04", Valor = "El Rosario", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 121, Codigo = "05", Valor = "Monte San Juan", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 122, Codigo = "06", Valor = "Oratorio de Concepción", CodigoDepartamento = "07", CodigoMunicipio = "17" },
            new CatDistrito { Id = 123, Codigo = "07", Valor = "San Bartolomé Perulapía", CodigoDepartamento = "07", CodigoMunicipio = "17" },
            new CatDistrito { Id = 124, Codigo = "08", Valor = "San Cristóbal", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 125, Codigo = "09", Valor = "San José Guayabal", CodigoDepartamento = "07", CodigoMunicipio = "17" },
            new CatDistrito { Id = 126, Codigo = "10", Valor = "San Pedro Perulapán", CodigoDepartamento = "07", CodigoMunicipio = "17" },
            new CatDistrito { Id = 127, Codigo = "11", Valor = "San Rafael Cedros", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 128, Codigo = "12", Valor = "San Ramón", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 129, Codigo = "13", Valor = "Santa Cruz Analquito", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 130, Codigo = "14", Valor = "Santa Cruz Michapa", CodigoDepartamento = "07", CodigoMunicipio = "18" },
            new CatDistrito { Id = 131, Codigo = "15", Valor = "Suchitoto", CodigoDepartamento = "07", CodigoMunicipio = "17" },
            new CatDistrito { Id = 132, Codigo = "16", Valor = "Tenancingo", CodigoDepartamento = "07", CodigoMunicipio = "18" },

            // --- LA PAZ (08) | O=23, C=24, E=25 ---
            new CatDistrito { Id = 133, Codigo = "01", Valor = "Cuyultitán", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 134, Codigo = "02", Valor = "El Rosario", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 135, Codigo = "03", Valor = "Jerusalén", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 136, Codigo = "04", Valor = "Mercedes La Ceiba", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 137, Codigo = "05", Valor = "Olocuilta", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 138, Codigo = "06", Valor = "Paraíso de Osorio", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 139, Codigo = "07", Valor = "San Antonio Masahuat", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 140, Codigo = "08", Valor = "San Emigdio", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 141, Codigo = "09", Valor = "San Francisco Chinameca", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 142, Codigo = "10", Valor = "San Juan Nonualco", CodigoDepartamento = "08", CodigoMunicipio = "25" },
            new CatDistrito { Id = 143, Codigo = "11", Valor = "San Juan Talpa", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 144, Codigo = "12", Valor = "San Juan Tepezontes", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 145, Codigo = "13", Valor = "San Luis Talpa", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 146, Codigo = "14", Valor = "San Miguel Tepezontes", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 147, Codigo = "15", Valor = "San Pedro Masahuat", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 148, Codigo = "16", Valor = "San Pedro Nonualco", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 149, Codigo = "17", Valor = "San Rafael Obrajuelo", CodigoDepartamento = "08", CodigoMunicipio = "25" },
            new CatDistrito { Id = 150, Codigo = "18", Valor = "Santa María Ostuma", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 151, Codigo = "19", Valor = "Santiago Nonualco", CodigoDepartamento = "08", CodigoMunicipio = "24" },
            new CatDistrito { Id = 152, Codigo = "20", Valor = "Tapalhuaca", CodigoDepartamento = "08", CodigoMunicipio = "23" },
            new CatDistrito { Id = 153, Codigo = "21", Valor = "Zacatecoluca", CodigoDepartamento = "08", CodigoMunicipio = "25" },
            new CatDistrito { Id = 154, Codigo = "22", Valor = "San Luis La Herradura", CodigoDepartamento = "08", CodigoMunicipio = "24" },

            // --- CABAÑAS (09) | O=10, E=11 ---
            new CatDistrito { Id = 155, Codigo = "01", Valor = "Cinquera", CodigoDepartamento = "09", CodigoMunicipio = "10" },
            new CatDistrito { Id = 156, Codigo = "02", Valor = "Guacotecti", CodigoDepartamento = "09", CodigoMunicipio = "11" },
            new CatDistrito { Id = 157, Codigo = "03", Valor = "Ilobasco", CodigoDepartamento = "09", CodigoMunicipio = "10" },
            new CatDistrito { Id = 158, Codigo = "04", Valor = "Jutiapa", CodigoDepartamento = "09", CodigoMunicipio = "10" },
            new CatDistrito { Id = 159, Codigo = "05", Valor = "San Isidro", CodigoDepartamento = "09", CodigoMunicipio = "11" },
            new CatDistrito { Id = 160, Codigo = "06", Valor = "Sensuntepeque", CodigoDepartamento = "09", CodigoMunicipio = "11" },
            new CatDistrito { Id = 161, Codigo = "07", Valor = "Tejutepeque", CodigoDepartamento = "09", CodigoMunicipio = "10" },
            new CatDistrito { Id = 162, Codigo = "08", Valor = "Victoria", CodigoDepartamento = "09", CodigoMunicipio = "11" },
            new CatDistrito { Id = 163, Codigo = "09", Valor = "Villa Dolores", CodigoDepartamento = "09", CodigoMunicipio = "11" },

            // --- SAN VICENTE (10) | N=14, S=15 ---
            new CatDistrito { Id = 164, Codigo = "01", Valor = "Apastepeque", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 165, Codigo = "02", Valor = "Guadalupe", CodigoDepartamento = "10", CodigoMunicipio = "15" },
            new CatDistrito { Id = 166, Codigo = "03", Valor = "San Cayetano Istepeque", CodigoDepartamento = "10", CodigoMunicipio = "15" },
            new CatDistrito { Id = 167, Codigo = "04", Valor = "Santa Clara", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 168, Codigo = "05", Valor = "Santo Domingo", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 169, Codigo = "06", Valor = "San Esteban Catarina", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 170, Codigo = "07", Valor = "San Ildefonso", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 171, Codigo = "08", Valor = "San Lorenzo", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 172, Codigo = "09", Valor = "San Sebastián", CodigoDepartamento = "10", CodigoMunicipio = "14" },
            new CatDistrito { Id = 173, Codigo = "10", Valor = "San Vicente", CodigoDepartamento = "10", CodigoMunicipio = "15" },
            new CatDistrito { Id = 174, Codigo = "11", Valor = "Tecoluca", CodigoDepartamento = "10", CodigoMunicipio = "15" },
            new CatDistrito { Id = 175, Codigo = "12", Valor = "Tepetitán", CodigoDepartamento = "10", CodigoMunicipio = "15" },
            new CatDistrito { Id = 176, Codigo = "13", Valor = "Verapaz", CodigoDepartamento = "10", CodigoMunicipio = "15" },

            // --- USULUTÁN (11) | N=24, E=25, O=26 ---
            new CatDistrito { Id = 177, Codigo = "01", Valor = "Alegría", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 178, Codigo = "02", Valor = "Berlín", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 179, Codigo = "03", Valor = "California", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 180, Codigo = "04", Valor = "Concepción Batres", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 181, Codigo = "05", Valor = "El Triunfo", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 182, Codigo = "06", Valor = "Ereguayquín", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 183, Codigo = "07", Valor = "Estanzuelas", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 184, Codigo = "08", Valor = "Jiquilisco", CodigoDepartamento = "11", CodigoMunicipio = "26" },
            new CatDistrito { Id = 185, Codigo = "09", Valor = "Jucuapa", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 186, Codigo = "10", Valor = "Jucuarán", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 187, Codigo = "11", Valor = "Mercedes Umaña", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 188, Codigo = "12", Valor = "Nueva Granada", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 189, Codigo = "13", Valor = "Ozatlán", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 190, Codigo = "14", Valor = "Puerto El Triunfo", CodigoDepartamento = "11", CodigoMunicipio = "26" },
            new CatDistrito { Id = 191, Codigo = "15", Valor = "San Agustín", CodigoDepartamento = "11", CodigoMunicipio = "26" },
            new CatDistrito { Id = 192, Codigo = "16", Valor = "San Buenaventura", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 193, Codigo = "17", Valor = "San Dionisio", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 194, Codigo = "18", Valor = "Santa Elena", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 195, Codigo = "19", Valor = "San Francisco Javier", CodigoDepartamento = "11", CodigoMunicipio = "26" },
            new CatDistrito { Id = 196, Codigo = "20", Valor = "Santa María", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 197, Codigo = "21", Valor = "Santiago de María", CodigoDepartamento = "11", CodigoMunicipio = "24" },
            new CatDistrito { Id = 198, Codigo = "22", Valor = "Tecapán", CodigoDepartamento = "11", CodigoMunicipio = "25" },
            new CatDistrito { Id = 199, Codigo = "23", Valor = "Usulután", CodigoDepartamento = "11", CodigoMunicipio = "25" },

            // --- SAN MIGUEL (12) | N=21, C=22, O=23 ---
            new CatDistrito { Id = 200, Codigo = "01", Valor = "Carolina", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 201, Codigo = "02", Valor = "Ciudad Barrios", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 202, Codigo = "03", Valor = "Comacarán", CodigoDepartamento = "12", CodigoMunicipio = "22" },
            new CatDistrito { Id = 203, Codigo = "04", Valor = "Chapeltique", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 204, Codigo = "05", Valor = "Chinameca", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 205, Codigo = "06", Valor = "Chirilagua", CodigoDepartamento = "12", CodigoMunicipio = "22" },
            new CatDistrito { Id = 206, Codigo = "07", Valor = "El Tránsito", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 207, Codigo = "08", Valor = "Lolotique", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 208, Codigo = "09", Valor = "Moncagua", CodigoDepartamento = "12", CodigoMunicipio = "22" },
            new CatDistrito { Id = 209, Codigo = "10", Valor = "Nueva Guadalupe", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 210, Codigo = "11", Valor = "Nuevo Edén de San Juan", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 211, Codigo = "12", Valor = "Quelepa", CodigoDepartamento = "12", CodigoMunicipio = "22" },
            new CatDistrito { Id = 212, Codigo = "13", Valor = "San Antonio del Mosco", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 213, Codigo = "14", Valor = "San Gerardo", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 214, Codigo = "15", Valor = "San Jorge", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 215, Codigo = "16", Valor = "San Luis de la Reina", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 216, Codigo = "17", Valor = "San Miguel", CodigoDepartamento = "12", CodigoMunicipio = "22" },
            new CatDistrito { Id = 217, Codigo = "18", Valor = "San Rafael Oriente", CodigoDepartamento = "12", CodigoMunicipio = "23" },
            new CatDistrito { Id = 218, Codigo = "19", Valor = "Sesori", CodigoDepartamento = "12", CodigoMunicipio = "21" },
            new CatDistrito { Id = 219, Codigo = "20", Valor = "Uluazapa", CodigoDepartamento = "12", CodigoMunicipio = "22" },

            // --- MORAZÁN (13) | N=27, S=28 ---
            new CatDistrito { Id = 220, Codigo = "01", Valor = "Arambala", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 221, Codigo = "02", Valor = "Cacaopera", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 222, Codigo = "03", Valor = "Corinto", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 223, Codigo = "04", Valor = "Chilanga", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 224, Codigo = "05", Valor = "Delicias de Concepción", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 225, Codigo = "06", Valor = "El Divisadero", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 226, Codigo = "07", Valor = "El Rosario", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 227, Codigo = "08", Valor = "Gualococti", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 228, Codigo = "09", Valor = "Guatajiagua", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 229, Codigo = "10", Valor = "Joateca", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 230, Codigo = "11", Valor = "Jocoaitique", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 231, Codigo = "12", Valor = "Jocoro", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 232, Codigo = "13", Valor = "Lolotiquillo", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 233, Codigo = "14", Valor = "Meanguera", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 234, Codigo = "15", Valor = "Osicala", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 235, Codigo = "16", Valor = "Perquín", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 236, Codigo = "17", Valor = "San Carlos", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 237, Codigo = "18", Valor = "San Fernando", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 238, Codigo = "19", Valor = "San Francisco Gotera", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 239, Codigo = "20", Valor = "San Isidro", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 240, Codigo = "21", Valor = "San Simón", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 241, Codigo = "22", Valor = "Sensembra", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 242, Codigo = "23", Valor = "Sociedad", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 243, Codigo = "24", Valor = "Torola", CodigoDepartamento = "13", CodigoMunicipio = "27" },
            new CatDistrito { Id = 244, Codigo = "25", Valor = "Yamabal", CodigoDepartamento = "13", CodigoMunicipio = "28" },
            new CatDistrito { Id = 245, Codigo = "26", Valor = "Yoloaiquín", CodigoDepartamento = "13", CodigoMunicipio = "28" },

            // --- LA UNIÓN (14) | N=19, S=20 ---
            new CatDistrito { Id = 246, Codigo = "01", Valor = "Anamorós", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 247, Codigo = "02", Valor = "Bolívar", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 248, Codigo = "03", Valor = "Concepción de Oriente", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 249, Codigo = "04", Valor = "Conchagua", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 250, Codigo = "05", Valor = "El Carmen", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 251, Codigo = "06", Valor = "El Sauce", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 252, Codigo = "07", Valor = "Intipucá", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 253, Codigo = "08", Valor = "La Unión", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 254, Codigo = "09", Valor = "Lislique", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 255, Codigo = "10", Valor = "Meanguera del Golfo", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 256, Codigo = "11", Valor = "Nueva Esparta", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 257, Codigo = "12", Valor = "Pasaquina", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 258, Codigo = "13", Valor = "Polorós", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 259, Codigo = "14", Valor = "San Alejo", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 260, Codigo = "15", Valor = "San José La Fuente", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 261, Codigo = "16", Valor = "Santa Rosa de Lima", CodigoDepartamento = "14", CodigoMunicipio = "19" },
            new CatDistrito { Id = 262, Codigo = "17", Valor = "Yayantique", CodigoDepartamento = "14", CodigoMunicipio = "20" },
            new CatDistrito { Id = 263, Codigo = "18", Valor = "Yucuaiquín", CodigoDepartamento = "14", CodigoMunicipio = "20" }
    };
}
